sudo: true

dist: trusty 

env:
  - URL=https://developer.salesforce.com/media/salesforce-cli/beta/sfdx-v5.7.4-57b4969-linux-amd64.tar.xz

addons:
  chrome: stable

before_install:
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
  - export PATH=/usr/local/heroku/bin:$PATH
  - openssl aes-256-cbc -K $encrypted_64814298f594_key -iv $encrypted_64814298f594_iv -in assets/server.key.enc -out assets/server.key -d  
  - wget -qO- $URL | tar xJf -
  - ./sfdx/install

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - heroku plugins:install salesforce-lightning-cli
  - export SFDX_DISABLE_ENCRYPTION=true
  - export SFDX_DOMAIN_RETRY=300
  - sfdx plugins:install salesforcedx@pre-release
  - sfdx force:auth:jwt:grant --clientid $CONSUMERKEY --jwtkeyfile assets/server.key --username $USERNAME --setdefaultdevhubusername

script:
  - sfdx force:org:create -s -f config/project-scratch-def.json -a travisciorg
  - lintout=$(heroku lightning:lint lightning-component-tests/main/default/aura/);if [[ $lintout =~ .*problem.*error.*warning ]]; then echo "$lintout"; false; fi  
  - sfdx force:source:push -u travisciorg
  - travis_wait runout=$(sfdx force:lightning:test:run); if [[ $? != 0 ]] || ! [[ $runout =~ Failing[[:blank:]]*0 ]]; then echo "$runout"; false; fi 
  - sfdx force:org:delete -u travisciorg -p
